name: Build Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Development
        env:
          NODE_ENV: production
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build -- --configuration development --base-href /ceccoff-angular-19-best-practicies/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-build
          path: dist/

      # Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init gh-pages
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages [skip ci]"
          git branch -M gh-pages
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
